# Generated by Django 5.2.16 on 2026-09-19 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0064_restore_tz_shifted_media_dates'),
    ]

    operations = [
        migrations.AddField(
            model_name='anime',
            name='notes_public',
            field=models.BooleanField(default=False, help_text='Show this note as a public review on your profile'),
        ),
        migrations.AddField(
            model_name='basicmedia',
            name='notes_public',
            field=models.BooleanField(default=False, help_text='Show this note as a public review on your profile'),
        ),
        migrations.AddField(
            model_name='boardgame',
            name='notes_public',
            field=models.BooleanField(default=False, help_text='Show this note as a public review on your profile'),
        ),
        migrations.AddField(
            model_name='book',
            name='notes_public',
            field=models.BooleanField(default=False, help_text='Show this note as a public review on your profile'),
        ),
        migrations.AddField(
            model_name='comic',
            name='notes_public',
            field=models.BooleanField(default=False, help_text='Show this note as a public review on your profile'),
        ),
        migrations.AddField(
            model_name='game',
            name='notes_public',
            field=models.BooleanField(default=False, help_text='Show this note as a public review on your profile'),
        ),
        migrations.AddField(
            model_name='historicalanime',
            name='notes_public',
            field=models.BooleanField(default=False, help_text='Show this note as a public review on your profile'),
        ),
        migrations.AddField(
            model_name='historicalbasicmedia',
            name='notes_public',
            field=models.BooleanField(default=False, help_text='Show this note as a public review on your profile'),
        ),
        migrations.AddField(
            model_name='historicalboardgame',
            name='notes_public',
            field=models.BooleanField(default=False, help_text='Show this note as a public review on your profile'),
        ),
        migrations.AddField(
            model_name='historicalbook',
            name='notes_public',
            field=models.BooleanField(default=False, help_text='Show this note as a public review on your profile'),
        ),
        migrations.AddField(
            model_name='historicalcomic',
            name='notes_public',
            field=models.BooleanField(default=False, help_text='Show this note as a public review on your profile'),
        ),
        migrations.AddField(
            model_name='historicalgame',
            name='notes_public',
            field=models.BooleanField(default=False, help_text='Show this note as a public review on your profile'),
        ),
        migrations.AddField(
            model_name='historicalmanga',
            name='notes_public',
            field=models.BooleanField(default=False, help_text='Show this note as a public review on your profile'),
        ),
        migrations.AddField(
            model_name='historicalmovie',
            name='notes_public',
            field=models.BooleanField(default=False, help_text='Show this note as a public review on your profile'),
        ),
        migrations.AddField(
            model_name='historicalseason',
            name='notes_public',
            field=models.BooleanField(default=False, help_text='Show this note as a public review on your profile'),
        ),
        migrations.AddField(
            model_name='historicaltv',
            name='notes_public',
            field=models.BooleanField(default=False, help_text='Show this note as a public review on your profile'),
        ),
        migrations.AddField(
            model_name='manga',
            name='notes_public',
            field=models.BooleanField(default=False, help_text='Show this note as a public review on your profile'),
        ),
        migrations.AddField(
            model_name='movie',
            name='notes_public',
            field=models.BooleanField(default=False, help_text='Show this note as a public review on your profile'),
        ),
        migrations.AddField(
            model_name='season',
            name='notes_public',
            field=models.BooleanField(default=False, help_text='Show this note as a public review on your profile'),
        ),
        migrations.AddField(
            model_name='tv',
            name='notes_public',
            field=models.BooleanField(default=False, help_text='Show this note as a public review on your profile'),
        ),
    ]
