# Generated by Django 5.2.16 on 2026-09-19 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0065_anime_notes_public_basicmedia_notes_public_and_more'),
        ('app', '0065_genre_item_genres'),
    ]

    operations = [
    ]
