# Generated by Django 5.2.2 on 2026-03-02 16:38

from django.db import migrations, models

BATCH_SIZE = 1000


def populate_list_item_id(apps, schema_editor):
    """Populate list_item_id for existing custom list items ordered by date_added."""
    CustomListItem = apps.get_model('lists', 'CustomListItem')

    custom_list_ids = (
        CustomListItem.objects.values_list('custom_list_id', flat=True)
        .distinct()
    )

    to_update = []
    for custom_list_id in custom_list_ids.iterator():
        list_items = (
            CustomListItem.objects.filter(custom_list_id=custom_list_id)
            .order_by('date_added', 'id')
            .only('id', 'list_item_id')
            .iterator()
        )
        for index, list_item in enumerate(list_items):
            list_item.list_item_id = index
            to_update.append(list_item)
            if len(to_update) >= BATCH_SIZE:
                CustomListItem.objects.bulk_update(to_update, ['list_item_id'])
                to_update = []
    if to_update:
        CustomListItem.objects.bulk_update(to_update, ['list_item_id'])


def reverse_populate_list_item_id(apps, schema_editor):
    """Reverse backfill by resetting list_item_id to null."""
    CustomListItem = apps.get_model('lists', 'CustomListItem')
    CustomListItem.objects.update(list_item_id=None)


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0051_migrate_simkl_periodoc_tasks'),
        ('lists', '0003_alter_customlist_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customlistitem',
            name='list_item_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.RunPython(
            code=populate_list_item_id,
            reverse_code=reverse_populate_list_item_id,
        ),
        migrations.AddConstraint(
            model_name='customlistitem',
            constraint=models.UniqueConstraint(fields=('custom_list', 'list_item_id'), name='lists_customlistitem_unique_list_item_id'),
        ),
    ]
