# Generated by Django 5.2.16 on 2026-09-18 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0003_alter_customlist_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customlist',
            name='is_featured',
            field=models.BooleanField(default=False, help_text='Show this list as a shelf on the public profile'),
        ),
        migrations.AddField(
            model_name='customlist',
            name='sort_order',
            field=models.PositiveIntegerField(blank=True, default=0, help_text='Manual position of the shelf (lower numbers come first)'),
        ),
    ]
