# Generated by Django 5.2.16 on 2026-09-22 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0004_customlist_is_featured_customlist_sort_order'),
        ('lists', '0004_customlistitem_list_item_id_and_more'),
    ]

    operations = [
    ]
