# Generated by Django 5.2.16 on 2026-09-18 23:01

import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0056_user_home_hide_unreleased'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, help_text='Profile picture (max 2 MB, JPEG/PNG/WEBP/GIF).', upload_to='avatars/', validators=[users.models.validate_avatar]),
        ),
        migrations.AddField(
            model_name='user',
            name='bio',
            field=models.TextField(blank=True, help_text='Short biography shown on your profile.', max_length=500),
        ),
        migrations.AddField(
            model_name='user',
            name='imdb',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='user',
            name='instagram',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='user',
            name='letterboxd',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='user',
            name='mastodon',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='user',
            name='trakt',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='user',
            name='twitter',
            field=models.URLField(blank=True),
        ),
    ]
