# Generated by Django 5.2.16 on 2026-09-19 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0057_user_avatar_user_bio_user_imdb_user_instagram_and_more'),
        ('users', '0057_user_suggestions_enabled_suggestion'),
    ]

    operations = [
    ]
