# Generated by Django 5.2.16 on 2026-09-27 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0066_merge_20260919_1030'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('users', '0058_merge_20260919_1030'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='user',
            name='list_detail_sort_valid',
        ),
        migrations.AlterField(
            model_name='user',
            name='list_detail_sort',
            field=models.CharField(choices=[('date_added', 'Date Added'), ('title', 'Title'), ('media_type', 'Media Type'), ('manual', 'Manual Order')], default='date_added', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.CheckConstraint(condition=models.Q(('list_detail_sort__in', ['date_added', 'title', 'media_type', 'manual'])), name='list_detail_sort_valid'),
        ),
    ]
