# Generated by Django 5.2.16 on 2026-09-27 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0059_remove_user_list_detail_sort_valid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_show_heatmap',
            field=models.BooleanField(default=True, help_text='Show your consumption heatmap on your public profile'),
        ),
        migrations.AddField(
            model_name='user',
            name='profile_show_reviews',
            field=models.BooleanField(default=True, help_text='Show your public reviews on your public profile'),
        ),
        migrations.AddField(
            model_name='user',
            name='profile_show_shelves',
            field=models.BooleanField(default=True, help_text='Show your featured shelves on your public profile'),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_private',
            field=models.BooleanField(default=False, help_text='Toggle profile visibility to anonymous users'),
        ),
    ]
