# Generated by Django 5.2.16 on 2026-09-23 11:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0066_merge_20260919_1030'),
        ('groups', '0002_groupinvitation'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupitem',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='groupitem',
            name='progress',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='groupitem',
            name='progressed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='groupitem',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='groupitem',
            name='status',
            field=models.CharField(choices=[('Completed', 'Completed'), ('In progress', 'In Progress'), ('Planning', 'Planning'), ('Paused', 'Paused'), ('Dropped', 'Dropped')], default='Planning', max_length=255),
        ),
        migrations.CreateModel(
            name='GroupEpisodeWatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('watched_at', models.DateTimeField(auto_now_add=True)),
                ('group_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watched_episodes', to='groups.groupitem')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_episode_watches', to='app.item')),
            ],
            options={
                'indexes': [models.Index(fields=['group_item'], name='groups_grou_group_i_ce1468_idx')],
                'constraints': [models.UniqueConstraint(fields=('group_item', 'item'), name='unique_group_episode_watch')],
            },
        ),
    ]
