# Generated by Django 5.2.16 on 2026-09-27 10:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0067_discards'),
        ('groups', '0003_group_progress'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupDiscard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('discarded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_discards_made', to=settings.AUTH_USER_MODEL)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discards', to='groups.group')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_discards', to='app.item')),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('group', 'item'), name='unique_group_discard')],
            },
        ),
    ]
