# Generated by Django 5.2.16 on 2026-10-05 19:42

import groups.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0004_discards'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='banner',
            field=models.ImageField(blank=True, help_text='Cover image (max 5 MB, JPEG/PNG/WEBP/GIF).', upload_to='group_banners/', validators=[groups.models.validate_banner]),
        ),
    ]
