# Generated by Django 5.2.16 on 2026-10-05 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0005_group_banner'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupmembership',
            name='quick_added_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
